const fs = require('fs');

const specMap = {
    "RAPL - PCHS - 35S": { "DISPLACEMENT": "35CC", "ENGINE POWER": "1.25 HP", "ENGINE TYPE": "4 STROKE", "FUEL": "PETROL" },
    "RAPL - PCHS - 35K": { "DISPLACEMENT": "35CC", "ENGINE POWER": "1.25 HP", "ENGINE TYPE": "4 STROKE", "FUEL": "PETROL" },
    "RAPL - PCHS - 52S": { "DISPLACEMENT": "52CC", "ENGINE POWER": "2HP", "ATTACHMENT": "TAP & GO, 2T, 80T", "ENGINE TYPE": "2 STROKE" },
    "RAPL-RH-700G": { "DISPLACEMENT": "212CC", "ENGINE MODEL": "170F PETROL", "TRANSMISSION": "GEAR", "FUEL": "PETROL" },
    "RAPL-RH-3800G": { "ENGINE MODEL": "170F PETROL", "ENGINE POWER": "212CC", "WEEDING BLADES": "7", "PUSH TYPE": "SELF PROPELLED" },
    "RAPL-SM-G50": { "ENGINE MODEL": "170F, 4 STROKE", "NO OF BLADES": "36 PCS", "CUTTING WIDTH": "50 CM", "FUEL": "PETROL" },
    "RAPL - EA - 6310": { "DISPLACEMENT": "63CC", "ENGINE POWER": "3HP", "ENGINE TYPE": "2 STROKE", "FUEL": "OIL MIX PETROL" },
    "RAPL-CC-9ZP-1.0": { "REQUIRED POWER": "3 HP", "SPEED OF MOTOR": "2800 R / MIN", "NO. OF BLADE": "4 PCS", "WEIGHT": "44 KG" },
    "RA-WC-192G-ES": { "ENGINE MODEL": "LC192F", "DISPLACEMENT": "459 CC", "MAX POWER": "10 KW", "FUEL": "PETROL" },
    "RAPL-WP-30R": { "ENGINE": "170F, 4 STROKE", "ENGINE POWER": "4 KW / PETROL", "MAX HEAD / SUCTION": "22M / 8M", "INLET / OUTLET": "3 INCH" },
    "RAPL-PS-26A": { "PUMP": "22MM", "PISTON": "3", "SUCTION": "14-26L/MIN", "RPM": "1000 TO 1200 RPM" },
    "RAPL-PS-168F-22B": { "ENGINE MODEL": "168F, 6.5 HP", "SPRAYER MODEL": "22 MM / 30 MM", "SPEED": "800-1200 RPM", "FUEL": "PETROL" },
    "RAPL-PS-1216": { "BATTERY": "12V 16AH", "TYPE": "BATTERY OPERATED", "SPEED CONTROLLER": "YES", "CHARGER": "1.7A" },
    "WC-205G-ES": { "ENGINE": "LC192F 459CC", "CAPACITY": "150 MM", "BLADE": "2+1", "WEIGHT": "165 KG" },
    "RAPL-KS-4131": { "DISPLACEMENT": "31CC, 4 STROKE", "ENGINE POWER": "1.25 HP", "TANK CAPACITY": "20L", "PUMP": "ABS PUMP" },
    "RAPL-POPS-35G": { "ENGINE": "35CC, 1 KW", "PRESSURE": "2.5 MPA", "FLOW RATE": "3-8 L/MIN", "PUMP": "ABS BRASS PUMP" },
    "DX-PCH - 35SP": { "DISPLACEMENT": "35CC", "ENGINE POWER": "1.25 HP", "CARRY TYPE": "SIDEPACK", "FUEL": "PETROL" },
    "RAPL-TB-52": { "DISPLACEMENT": "52 CC", "ENGINE POWER": "2 HP / 7000 RPM", "ATTACHMENT": "TAP & GO, 2T", "FUEL": "OIL MIX PETROL" },
    "RAPL-TH-2105": { "BATTERY": "DC 21V, 5.2AH", "RUNNING TIME": "3-4 HOURS", "MOTOR POWER": "300 W", "BLADE LENGTH": "300 MM" },
    "WA20 - WA30": { "ENGINE": "170F PETROL", "MAX HEAD": "22M", "INLET / OUTLET": "2 INCH & 3 INCH", "FUEL": "PETROL" },
    "MY-CC-0.4": { "REQUIRED POWER": "3 HP SINGLE PHASE", "SPEED OF MOTOR": "2800 R / MIN", "NO. OF BLADE": "4 PCS (MANGANESE STEEL)", "WEIGHT": "70 KGS (WITH MOTOR)" },
    "MY-370G": { "DISPLACEMENT": "212CC / PETROL", "ENGINE POWER": "4 KW 3600 RPM", "TYRE": "4.0 - 8", "BLADES (DRY LAND)": "32 PCS" },
    "MY-380G": { "DISPLACEMENT": "212CC / PETROL", "ENGINE POWER": "4 KW / 3600 RPM", "TYRE": "ATV TYRE 19*7*8", "BLADES (DRY LAND)": "32 PCS" },
    "MY-470G": { "DISPLACEMENT/FUEL": "212CC / PETROL", "ENGINE MODEL": "170F PETROL", "TRANSMISSION": "GEAR", "BLADES (DRY LAND)": "32 PCS" },
    "MY-BC-45G": { "DISPLACEMENT": "41.5 CC PETROL", "ENGINE POWER": "1.75 HP", "CARRY TYPE": "SIDE PACK", "ATTACHMENTS": "TAP & GO, 2T" },
    "DX-PCH 52SP": { "DISPLACEMENT": "52 CC PETROL", "ENGINE POWER": "2HP", "CARRY TYPE": "SIDE PACK", "ATTACHMENTS": "TAP & GO, 2T, 80T" },
    "MY - HPW - 1450": { "WORKING PRESSURE": "UPTO 90 BAR", "POWER": "1500 W", "VOLTAGE": "220V", "AUTO STOP (YES/NO)": "YES" },
    "MY - 300G": { "DISPLACEMENT": "63 CC PETROL", "ENGINE POWER": "3HP", "CARRY TYPE": "TROLLY", "RPM": "7000 RPM" },
    "MY-AC-20L": { "POWER": "1200W", "VOLTAGE": "240V-50Hz", "VACUUM": "300mbr", "CAPACITY": "20L" },
    "MY-8PRO-30L": { "VOLTAGE": "220V", "POWER": "2.5 HP", "PRESSURE": "8 BAR / 115 PSI", "TANK": "30 L" },
    "MY-CS-6010-18": { "DISPLACEMENT": "58CC", "GUIDE BAR": "18 INCH", "IDLE SPEED": "3200+200 RPM", "OIL MIX RATIO": "1:25" },
    "RAPL-MS-12T": { "MODEL NO.": "RAPL-MS-12T LONG" },
    "RAPL-W80": { "DISPLACEMENT": "48 CC", "FLOW RATE": "10 - 35 L/HR", "FRAME MATERIAL": "8K SS", "WEIGHT": "9.5 KG" },
    "RAPL - RM - 6N40": { "PRODUCT NAME": "RICE MILL", "POWER (KW)": "1.8", "GRINDING CAPACITY": "120 - 150 KG", "WEIGHT": "50 KG" },
    "RAPL-KS-3416": { "DISPLACEMENT": "35 CC / 2 STROKE", "ENGINE POWER": "1.25 HP / 3000 RPM", "PRESSURE": "1.5 - 2.5 MPA", "WATER FLOW": "3 - 8 LTR MIN", "PUMP": "HEAVY BRASS", "BELT": "LEATHER BELT", "TANK CAPACITY": "15 LITER" },
    "GX35-GX50": { "ENGINE MODEL": "35 CC / 50 CC", "FUEL TANK CAPACITY": "0.63 LIT", "OIL CAPACITY": "100 ML", "ATTACHMENT": "5 PCS", "CARRY MODEL": "SIDE PACK", "WARRANTY": "6 MONTHS", "WEIGHT": "6 KG" },
    "RAPL - GE - 168F": { "DISPLACEMENT": "196 CC / 4KW", "RPM": "3600 RPM", "FUEL": "PETROL", "WEIGHT": "16 KG" },
    "RAPL - BC - 35E": { "DISPLACEMENT": "35CC", "ENGINE POWER": "1.25 HP / 7000 RPM", "FUEL": "PETROL", "ENGINE TYPE": "4 STROKE" },
    "RAPL - RA170": { "DISPLACEMENT": "212 CC / 7HP", "RPM": "3600 RPM", "FUEL": "PETROL / 3.5 L", "WEIGHT": "16 KG" },
    "RAPL - BC - 52E": { "DISPLACEMENT": "52CC", "ENGINE POWER": "2 HP / 7000 RPM", "FUEL": "PETROL + 2T OIL", "ENGINE TYPE": "2 STROKE" }
};

const file = 'src/products.json';
const data = JSON.parse(fs.readFileSync(file, 'utf8'));

data.forEach(p => {
    let found = false;
    for (const key in specMap) {
        if (p.name.includes(key)) {
            p.specs = specMap[key];
            found = true;
            break;
        }
    }
});

fs.writeFileSync(file, JSON.stringify(data, null, 4));
console.log('done');
